/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.dao.jooq.tables;


import java.time.LocalDateTime;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function10;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sf.financialreports.dao.jooq.Finances;
import sf.financialreports.dao.jooq.Keys;
import sf.financialreports.dao.jooq.tables.records.AuditRecord;


/**
 * Аудит сервиса
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Audit extends TableImpl<AuditRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>finances.audit</code>
     */
    public static final Audit AUDIT = new Audit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuditRecord> getRecordType() {
        return AuditRecord.class;
    }

    /**
     * The column <code>finances.audit.id</code>. Идентификатор записи
     */
    public final TableField<AuditRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "Идентификатор записи");

    /**
     * The column <code>finances.audit.oper_uid</code>. Уникальный идентификатор
     * операции
     */
    public final TableField<AuditRecord, UUID> OPER_UID = createField(DSL.name("oper_uid"), SQLDataType.UUID.nullable(false), this, "Уникальный идентификатор операции");

    /**
     * The column <code>finances.audit.user_id</code>. Идентификатор
     * пользователя
     */
    public final TableField<AuditRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID, this, "Идентификатор пользователя");

    /**
     * The column <code>finances.audit.message_type</code>. Тип сообщения
     */
    public final TableField<AuditRecord, String> MESSAGE_TYPE = createField(DSL.name("message_type"), SQLDataType.VARCHAR(50).nullable(false), this, "Тип сообщения");

    /**
     * The column <code>finances.audit.request_type</code>. Тип запроса
     */
    public final TableField<AuditRecord, String> REQUEST_TYPE = createField(DSL.name("request_type"), SQLDataType.VARCHAR(100).nullable(false), this, "Тип запроса");

    /**
     * The column <code>finances.audit.request_path</code>. Путь запроса
     */
    public final TableField<AuditRecord, String> REQUEST_PATH = createField(DSL.name("request_path"), SQLDataType.VARCHAR(100).nullable(false), this, "Путь запроса");

    /**
     * The column <code>finances.audit.request_headers</code>. Заголовки запроса
     */
    public final TableField<AuditRecord, String> REQUEST_HEADERS = createField(DSL.name("request_headers"), SQLDataType.VARCHAR.nullable(false), this, "Заголовки запроса");

    /**
     * The column <code>finances.audit.request_params</code>. Параметры запроса
     */
    public final TableField<AuditRecord, String> REQUEST_PARAMS = createField(DSL.name("request_params"), SQLDataType.VARCHAR(255), this, "Параметры запроса");

    /**
     * The column <code>finances.audit.payload</code>. Тело запроса
     */
    public final TableField<AuditRecord, String> PAYLOAD = createField(DSL.name("payload"), SQLDataType.VARCHAR, this, "Тело запроса");

    /**
     * The column <code>finances.audit.created_at</code>. Дата создания записи
     */
    public final TableField<AuditRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "Дата создания записи");

    private Audit(Name alias, Table<AuditRecord> aliased) {
        this(alias, aliased, null);
    }

    private Audit(Name alias, Table<AuditRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Аудит сервиса"), TableOptions.table());
    }

    /**
     * Create an aliased <code>finances.audit</code> table reference
     */
    public Audit(String alias) {
        this(DSL.name(alias), AUDIT);
    }

    /**
     * Create an aliased <code>finances.audit</code> table reference
     */
    public Audit(Name alias) {
        this(alias, AUDIT);
    }

    /**
     * Create a <code>finances.audit</code> table reference
     */
    public Audit() {
        this(DSL.name("audit"), null);
    }

    public <O extends Record> Audit(Table<O> child, ForeignKey<O, AuditRecord> key) {
        super(child, key, AUDIT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Finances.FINANCES;
    }

    @Override
    public UniqueKey<AuditRecord> getPrimaryKey() {
        return Keys.PK_AUDIT;
    }

    @Override
    public Audit as(String alias) {
        return new Audit(DSL.name(alias), this);
    }

    @Override
    public Audit as(Name alias) {
        return new Audit(alias, this);
    }

    @Override
    public Audit as(Table<?> alias) {
        return new Audit(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Audit rename(String name) {
        return new Audit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Audit rename(Name name) {
        return new Audit(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Audit rename(Table<?> name) {
        return new Audit(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<UUID, UUID, UUID, String, String, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function10<? super UUID, ? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function10<? super UUID, ? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
