/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.dao.jooq.tables;


import java.time.LocalDateTime;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sf.financialreports.dao.jooq.Finances;
import sf.financialreports.dao.jooq.Keys;
import sf.financialreports.dao.jooq.tables.records.IntegrationLogRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IntegrationLog extends TableImpl<IntegrationLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>finances.integration_log</code>
     */
    public static final IntegrationLog INTEGRATION_LOG = new IntegrationLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IntegrationLogRecord> getRecordType() {
        return IntegrationLogRecord.class;
    }

    /**
     * The column <code>finances.integration_log.id</code>.
     */
    public final TableField<IntegrationLogRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>finances.integration_log.oper_uid</code>.
     */
    public final TableField<IntegrationLogRecord, UUID> OPER_UID = createField(DSL.name("oper_uid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>finances.integration_log.request_type</code>.
     */
    public final TableField<IntegrationLogRecord, String> REQUEST_TYPE = createField(DSL.name("request_type"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>finances.integration_log.created_at</code>.
     */
    public final TableField<IntegrationLogRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>finances.integration_log.payload</code>.
     */
    public final TableField<IntegrationLogRecord, JSON> PAYLOAD = createField(DSL.name("payload"), SQLDataType.JSON, this, "");

    /**
     * The column <code>finances.integration_log.request_params</code>.
     */
    public final TableField<IntegrationLogRecord, String> REQUEST_PARAMS = createField(DSL.name("request_params"), SQLDataType.VARCHAR(255), this, "");

    private IntegrationLog(Name alias, Table<IntegrationLogRecord> aliased) {
        this(alias, aliased, null);
    }

    private IntegrationLog(Name alias, Table<IntegrationLogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>finances.integration_log</code> table reference
     */
    public IntegrationLog(String alias) {
        this(DSL.name(alias), INTEGRATION_LOG);
    }

    /**
     * Create an aliased <code>finances.integration_log</code> table reference
     */
    public IntegrationLog(Name alias) {
        this(alias, INTEGRATION_LOG);
    }

    /**
     * Create a <code>finances.integration_log</code> table reference
     */
    public IntegrationLog() {
        this(DSL.name("integration_log"), null);
    }

    public <O extends Record> IntegrationLog(Table<O> child, ForeignKey<O, IntegrationLogRecord> key) {
        super(child, key, INTEGRATION_LOG);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Finances.FINANCES;
    }

    @Override
    public Identity<IntegrationLogRecord, Long> getIdentity() {
        return (Identity<IntegrationLogRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<IntegrationLogRecord> getPrimaryKey() {
        return Keys.PK_INTEGRATION_LOG;
    }

    @Override
    public IntegrationLog as(String alias) {
        return new IntegrationLog(DSL.name(alias), this);
    }

    @Override
    public IntegrationLog as(Name alias) {
        return new IntegrationLog(alias, this);
    }

    @Override
    public IntegrationLog as(Table<?> alias) {
        return new IntegrationLog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public IntegrationLog rename(String name) {
        return new IntegrationLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IntegrationLog rename(Name name) {
        return new IntegrationLog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public IntegrationLog rename(Table<?> name) {
        return new IntegrationLog(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, UUID, String, LocalDateTime, JSON, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Long, ? super UUID, ? super String, ? super LocalDateTime, ? super JSON, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Long, ? super UUID, ? super String, ? super LocalDateTime, ? super JSON, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
