/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.dao.jooq.tables;


import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import sf.financialreports.dao.jooq.Finances;
import sf.financialreports.dao.jooq.Indexes;
import sf.financialreports.dao.jooq.Keys;
import sf.financialreports.dao.jooq.enums.TransactionStatus;
import sf.financialreports.dao.jooq.enums.UserType;
import sf.financialreports.dao.jooq.tables.records.TransactionRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;


/**
 * Таблица транзакций
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transaction extends TableImpl<TransactionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>finances.transaction</code>
     */
    public static final Transaction TRANSACTION = new Transaction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TransactionRecord> getRecordType() {
        return TransactionRecord.class;
    }

    /**
     * The column <code>finances.transaction.id</code>. Идентификатор транзакции
     */
    public final TableField<TransactionRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "Идентификатор транзакции");

    /**
     * The column <code>finances.transaction.user_id</code>. Идентификатор
     * пользователя
     */
    public final TableField<TransactionRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "Идентификатор пользователя");

    /**
     * The column <code>finances.transaction.category_name</code>. Идентификатор
     * категории
     */
    public final TableField<TransactionRecord, String> CATEGORY_NAME = createField(DSL.name("category_name"), SQLDataType.VARCHAR(100).nullable(false), this, "Идентификатор категории");

    /**
     * The column <code>finances.transaction.date</code>. Дата совершения
     * транзакции
     */
    public final TableField<TransactionRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE.nullable(false), this, "Дата совершения транзакции");

    /**
     * The column <code>finances.transaction.description</code>. Описание
     * транзакции
     */
    public final TableField<TransactionRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "Описание транзакции");

    /**
     * The column <code>finances.transaction.amount</code>. Сумма транзакции
     */
    public final TableField<TransactionRecord, BigDecimal> AMOUNT = createField(DSL.name("amount"), SQLDataType.NUMERIC(15, 5).nullable(false), this, "Сумма транзакции");

    /**
     * The column <code>finances.transaction.status</code>. Статус транзакции
     */
    public final TableField<TransactionRecord, TransactionStatus> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(sf.financialreports.dao.jooq.enums.TransactionStatus.class), this, "Статус транзакции");

    /**
     * The column <code>finances.transaction.sender_bank</code>. Название
     * банка-отправителя
     */
    public final TableField<TransactionRecord, String> SENDER_BANK = createField(DSL.name("sender_bank"), SQLDataType.VARCHAR(100), this, "Название банка-отправителя");

    /**
     * The column <code>finances.transaction.sender_account</code>. Счет
     * отправителя
     */
    public final TableField<TransactionRecord, String> SENDER_ACCOUNT = createField(DSL.name("sender_account"), SQLDataType.VARCHAR(30), this, "Счет отправителя");

    /**
     * The column <code>finances.transaction.receiver_user_type</code>. Тип
     * получателя
     */
    public final TableField<TransactionRecord, UserType> RECEIVER_USER_TYPE = createField(DSL.name("receiver_user_type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(sf.financialreports.dao.jooq.enums.UserType.class), this, "Тип получателя");

    /**
     * The column <code>finances.transaction.receiver_bank</code>. Название
     * банка-получателя
     */
    public final TableField<TransactionRecord, String> RECEIVER_BANK = createField(DSL.name("receiver_bank"), SQLDataType.VARCHAR(100), this, "Название банка-получателя");

    /**
     * The column <code>finances.transaction.receiver_account</code>. Счет
     * получателя
     */
    public final TableField<TransactionRecord, String> RECEIVER_ACCOUNT = createField(DSL.name("receiver_account"), SQLDataType.VARCHAR(30), this, "Счет получателя");

    /**
     * The column <code>finances.transaction.receiver_inn</code>. ИНН получателя
     */
    public final TableField<TransactionRecord, String> RECEIVER_INN = createField(DSL.name("receiver_inn"), SQLDataType.VARCHAR(12), this, "ИНН получателя");

    /**
     * The column <code>finances.transaction.receiver_phone</code>. Номер
     * телефона получателя
     */
    public final TableField<TransactionRecord, String> RECEIVER_PHONE = createField(DSL.name("receiver_phone"), SQLDataType.VARCHAR(20), this, "Номер телефона получателя");

    /**
     * The column <code>finances.transaction.created_at</code>. Дата создания
     * транзакции
     */
    public final TableField<TransactionRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "Дата создания транзакции");

    private Transaction(Name alias, Table<TransactionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Transaction(Name alias, Table<TransactionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Таблица транзакций"), TableOptions.table());
    }

    /**
     * Create an aliased <code>finances.transaction</code> table reference
     */
    public Transaction(String alias) {
        this(DSL.name(alias), TRANSACTION);
    }

    /**
     * Create an aliased <code>finances.transaction</code> table reference
     */
    public Transaction(Name alias) {
        this(alias, TRANSACTION);
    }

    /**
     * Create a <code>finances.transaction</code> table reference
     */
    public Transaction() {
        this(DSL.name("transaction"), null);
    }

    public <O extends Record> Transaction(Table<O> child, ForeignKey<O, TransactionRecord> key) {
        super(child, key, TRANSACTION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Finances.FINANCES;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_TRANSACTION_USER_ID);
    }

    @Override
    public UniqueKey<TransactionRecord> getPrimaryKey() {
        return Keys.PK_TRANSACTION;
    }

    @Override
    public List<ForeignKey<TransactionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TRANSACTION__FK_USER_ID, Keys.TRANSACTION__TRANSACTION_CATEGORY_FKEY);
    }

    private transient User _user;
    private transient Category _category;

    /**
     * Get the implicit join path to the <code>finances.user</code> table.
     */
    public User user() {
        if (_user == null)
            _user = new User(this, Keys.TRANSACTION__FK_USER_ID);

        return _user;
    }

    /**
     * Get the implicit join path to the <code>finances.category</code> table.
     */
    public Category category() {
        if (_category == null)
            _category = new Category(this, Keys.TRANSACTION__TRANSACTION_CATEGORY_FKEY);

        return _category;
    }

    @Override
    public List<Check<TransactionRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("transaction_amount_check"), "((amount >= (0)::numeric))", true)
        );
    }

    @Override
    public Transaction as(String alias) {
        return new Transaction(DSL.name(alias), this);
    }

    @Override
    public Transaction as(Name alias) {
        return new Transaction(alias, this);
    }

    @Override
    public Transaction as(Table<?> alias) {
        return new Transaction(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Transaction rename(String name) {
        return new Transaction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Transaction rename(Name name) {
        return new Transaction(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Transaction rename(Table<?> name) {
        return new Transaction(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row15 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row15<UUID, UUID, String, LocalDate, String, BigDecimal, TransactionStatus, String, String, UserType, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function15<? super UUID, ? super UUID, ? super String, ? super LocalDate, ? super String, ? super BigDecimal, ? super TransactionStatus, ? super String, ? super String, ? super UserType, ? super String, ? super String, ? super String, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function15<? super UUID, ? super UUID, ? super String, ? super LocalDate, ? super String, ? super BigDecimal, ? super TransactionStatus, ? super String, ? super String, ? super UserType, ? super String, ? super String, ? super String, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
