/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.dao.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import sf.financialreports.dao.jooq.tables.Audit;

import java.time.LocalDateTime;
import java.util.UUID;


/**
 * Аудит сервиса
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AuditRecord extends UpdatableRecordImpl<AuditRecord> implements Record10<UUID, UUID, UUID, String, String, String, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached AuditRecord
     */
    public AuditRecord() {
        super(Audit.AUDIT);
    }

    /**
     * Create a detached, initialised AuditRecord
     */
    public AuditRecord(UUID id, UUID operUid, UUID userId, String messageType, String requestType, String requestPath, String requestHeaders, String requestParams, String payload, LocalDateTime createdAt) {
        super(Audit.AUDIT);

        setId(id);
        setOperUid(operUid);
        setUserId(userId);
        setMessageType(messageType);
        setRequestType(requestType);
        setRequestPath(requestPath);
        setRequestHeaders(requestHeaders);
        setRequestParams(requestParams);
        setPayload(payload);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Getter for <code>finances.audit.id</code>. Идентификатор записи
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>finances.audit.id</code>. Идентификатор записи
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>finances.audit.oper_uid</code>. Уникальный идентификатор
     * операции
     */
    public UUID getOperUid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>finances.audit.oper_uid</code>. Уникальный идентификатор
     * операции
     */
    public void setOperUid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>finances.audit.user_id</code>. Идентификатор
     * пользователя
     */
    public UUID getUserId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>finances.audit.user_id</code>. Идентификатор
     * пользователя
     */
    public void setUserId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>finances.audit.message_type</code>. Тип сообщения
     */
    public String getMessageType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>finances.audit.message_type</code>. Тип сообщения
     */
    public void setMessageType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>finances.audit.request_type</code>. Тип запроса
     */
    public String getRequestType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>finances.audit.request_type</code>. Тип запроса
     */
    public void setRequestType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>finances.audit.request_path</code>. Путь запроса
     */
    public String getRequestPath() {
        return (String) get(5);
    }

    /**
     * Setter for <code>finances.audit.request_path</code>. Путь запроса
     */
    public void setRequestPath(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>finances.audit.request_headers</code>. Заголовки запроса
     */
    public String getRequestHeaders() {
        return (String) get(6);
    }

    /**
     * Setter for <code>finances.audit.request_headers</code>. Заголовки запроса
     */
    public void setRequestHeaders(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>finances.audit.request_params</code>. Параметры запроса
     */
    public String getRequestParams() {
        return (String) get(7);
    }

    /**
     * Setter for <code>finances.audit.request_params</code>. Параметры запроса
     */
    public void setRequestParams(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>finances.audit.payload</code>. Тело запроса
     */
    public String getPayload() {
        return (String) get(8);
    }

    /**
     * Setter for <code>finances.audit.payload</code>. Тело запроса
     */
    public void setPayload(String value) {
        set(8, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<UUID, UUID, UUID, String, String, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<UUID, UUID, UUID, String, String, String, String, String, String, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Audit.AUDIT.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Audit.AUDIT.OPER_UID;
    }

    @Override
    public Field<UUID> field3() {
        return Audit.AUDIT.USER_ID;
    }

    @Override
    public Field<String> field4() {
        return Audit.AUDIT.MESSAGE_TYPE;
    }

    @Override
    public Field<String> field5() {
        return Audit.AUDIT.REQUEST_TYPE;
    }

    @Override
    public Field<String> field6() {
        return Audit.AUDIT.REQUEST_PATH;
    }

    @Override
    public Field<String> field7() {
        return Audit.AUDIT.REQUEST_HEADERS;
    }

    @Override
    public Field<String> field8() {
        return Audit.AUDIT.REQUEST_PARAMS;
    }

    @Override
    public Field<String> field9() {
        return Audit.AUDIT.PAYLOAD;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return Audit.AUDIT.CREATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getOperUid();
    }

    @Override
    public UUID component3() {
        return getUserId();
    }

    @Override
    public String component4() {
        return getMessageType();
    }

    @Override
    public String component5() {
        return getRequestType();
    }

    @Override
    public String component6() {
        return getRequestPath();
    }

    @Override
    public String component7() {
        return getRequestHeaders();
    }

    @Override
    public String component8() {
        return getRequestParams();
    }

    @Override
    public String component9() {
        return getPayload();
    }

    @Override
    public LocalDateTime component10() {
        return getCreatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getOperUid();
    }

    @Override
    public UUID value3() {
        return getUserId();
    }

    @Override
    public String value4() {
        return getMessageType();
    }

    @Override
    public String value5() {
        return getRequestType();
    }

    @Override
    public String value6() {
        return getRequestPath();
    }

    @Override
    public String value7() {
        return getRequestHeaders();
    }

    @Override
    public String value8() {
        return getRequestParams();
    }

    @Override
    public String value9() {
        return getPayload();
    }

    @Override
    public LocalDateTime value10() {
        return getCreatedAt();
    }

    @Override
    public AuditRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public AuditRecord value2(UUID value) {
        setOperUid(value);
        return this;
    }

    @Override
    public AuditRecord value3(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public AuditRecord value4(String value) {
        setMessageType(value);
        return this;
    }

    @Override
    public AuditRecord value5(String value) {
        setRequestType(value);
        return this;
    }

    @Override
    public AuditRecord value6(String value) {
        setRequestPath(value);
        return this;
    }

    @Override
    public AuditRecord value7(String value) {
        setRequestHeaders(value);
        return this;
    }

    @Override
    public AuditRecord value8(String value) {
        setRequestParams(value);
        return this;
    }

    @Override
    public AuditRecord value9(String value) {
        setPayload(value);
        return this;
    }

    @Override
    public AuditRecord value10(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AuditRecord values(UUID value1, UUID value2, UUID value3, String value4, String value5, String value6, String value7, String value8, String value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>finances.audit.created_at</code>. Дата создания записи
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>finances.audit.created_at</code>. Дата создания записи
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }
}
