/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.dao.jooq.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import sf.financialreports.dao.jooq.enums.CategoryType;
import sf.financialreports.dao.jooq.tables.Category;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryRecord extends UpdatableRecordImpl<CategoryRecord> implements Record6<UUID, UUID, String, String, CategoryType, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>finances.category.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>finances.category.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>finances.category.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>finances.category.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>finances.category.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>finances.category.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>finances.category.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>finances.category.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>finances.category.type</code>.
     */
    public void setType(CategoryType value) {
        set(4, value);
    }

    /**
     * Getter for <code>finances.category.type</code>.
     */
    public CategoryType getType() {
        return (CategoryType) get(4);
    }

    /**
     * Setter for <code>finances.category.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>finances.category.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, String, String, CategoryType, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, UUID, String, String, CategoryType, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Category.CATEGORY.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Category.CATEGORY.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Category.CATEGORY.NAME;
    }

    @Override
    public Field<String> field4() {
        return Category.CATEGORY.DESCRIPTION;
    }

    @Override
    public Field<CategoryType> field5() {
        return Category.CATEGORY.TYPE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Category.CATEGORY.CREATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public CategoryType component5() {
        return getType();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public CategoryType value5() {
        return getType();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public CategoryRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public CategoryRecord value2(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public CategoryRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public CategoryRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public CategoryRecord value5(CategoryType value) {
        setType(value);
        return this;
    }

    @Override
    public CategoryRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CategoryRecord values(UUID value1, UUID value2, String value3, String value4, CategoryType value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CategoryRecord
     */
    public CategoryRecord() {
        super(Category.CATEGORY);
    }

    /**
     * Create a detached, initialised CategoryRecord
     */
    public CategoryRecord(UUID id, UUID userId, String name, String description, CategoryType type, LocalDateTime createdAt) {
        super(Category.CATEGORY);

        setId(id);
        setUserId(userId);
        setName(name);
        setDescription(description);
        setType(type);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
