/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.dao.jooq.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import sf.financialreports.dao.jooq.tables.IntegrationLog;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IntegrationLogRecord extends UpdatableRecordImpl<IntegrationLogRecord> implements Record6<Long, UUID, String, LocalDateTime, JSON, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>finances.integration_log.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>finances.integration_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>finances.integration_log.oper_uid</code>.
     */
    public void setOperUid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>finances.integration_log.oper_uid</code>.
     */
    public UUID getOperUid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>finances.integration_log.request_type</code>.
     */
    public void setRequestType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>finances.integration_log.request_type</code>.
     */
    public String getRequestType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>finances.integration_log.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>finances.integration_log.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>finances.integration_log.payload</code>.
     */
    public void setPayload(JSON value) {
        set(4, value);
    }

    /**
     * Getter for <code>finances.integration_log.payload</code>.
     */
    public JSON getPayload() {
        return (JSON) get(4);
    }

    /**
     * Setter for <code>finances.integration_log.request_params</code>.
     */
    public void setRequestParams(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>finances.integration_log.request_params</code>.
     */
    public String getRequestParams() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, UUID, String, LocalDateTime, JSON, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, UUID, String, LocalDateTime, JSON, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return IntegrationLog.INTEGRATION_LOG.ID;
    }

    @Override
    public Field<UUID> field2() {
        return IntegrationLog.INTEGRATION_LOG.OPER_UID;
    }

    @Override
    public Field<String> field3() {
        return IntegrationLog.INTEGRATION_LOG.REQUEST_TYPE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return IntegrationLog.INTEGRATION_LOG.CREATED_AT;
    }

    @Override
    public Field<JSON> field5() {
        return IntegrationLog.INTEGRATION_LOG.PAYLOAD;
    }

    @Override
    public Field<String> field6() {
        return IntegrationLog.INTEGRATION_LOG.REQUEST_PARAMS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getOperUid();
    }

    @Override
    public String component3() {
        return getRequestType();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public JSON component5() {
        return getPayload();
    }

    @Override
    public String component6() {
        return getRequestParams();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getOperUid();
    }

    @Override
    public String value3() {
        return getRequestType();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public JSON value5() {
        return getPayload();
    }

    @Override
    public String value6() {
        return getRequestParams();
    }

    @Override
    public IntegrationLogRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public IntegrationLogRecord value2(UUID value) {
        setOperUid(value);
        return this;
    }

    @Override
    public IntegrationLogRecord value3(String value) {
        setRequestType(value);
        return this;
    }

    @Override
    public IntegrationLogRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public IntegrationLogRecord value5(JSON value) {
        setPayload(value);
        return this;
    }

    @Override
    public IntegrationLogRecord value6(String value) {
        setRequestParams(value);
        return this;
    }

    @Override
    public IntegrationLogRecord values(Long value1, UUID value2, String value3, LocalDateTime value4, JSON value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IntegrationLogRecord
     */
    public IntegrationLogRecord() {
        super(IntegrationLog.INTEGRATION_LOG);
    }

    /**
     * Create a detached, initialised IntegrationLogRecord
     */
    public IntegrationLogRecord(Long id, UUID operUid, String requestType, LocalDateTime createdAt, JSON payload, String requestParams) {
        super(IntegrationLog.INTEGRATION_LOG);

        setId(id);
        setOperUid(operUid);
        setRequestType(requestType);
        setCreatedAt(createdAt);
        setPayload(payload);
        setRequestParams(requestParams);
        resetChangedOnNotNull();
    }
}
