/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.dao.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;
import sf.financialreports.dao.jooq.enums.TransactionStatus;
import sf.financialreports.dao.jooq.enums.UserType;
import sf.financialreports.dao.jooq.tables.Transaction;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionRecord extends UpdatableRecordImpl<TransactionRecord> implements Record15<UUID, UUID, String, LocalDate, String, BigDecimal, TransactionStatus, String, String, UserType, String, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>finances.transaction.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>finances.transaction.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>finances.transaction.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>finances.transaction.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>finances.transaction.category_name</code>.
     */
    public void setCategoryName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>finances.transaction.category_name</code>.
     */
    public String getCategoryName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>finances.transaction.date</code>.
     */
    public void setDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>finances.transaction.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>finances.transaction.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>finances.transaction.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>finances.transaction.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>finances.transaction.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>finances.transaction.status</code>.
     */
    public void setStatus(TransactionStatus value) {
        set(6, value);
    }

    /**
     * Getter for <code>finances.transaction.status</code>.
     */
    public TransactionStatus getStatus() {
        return (TransactionStatus) get(6);
    }

    /**
     * Setter for <code>finances.transaction.sender_bank</code>.
     */
    public void setSenderBank(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>finances.transaction.sender_bank</code>.
     */
    public String getSenderBank() {
        return (String) get(7);
    }

    /**
     * Setter for <code>finances.transaction.sender_account</code>.
     */
    public void setSenderAccount(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>finances.transaction.sender_account</code>.
     */
    public String getSenderAccount() {
        return (String) get(8);
    }

    /**
     * Create a detached TransactionRecord
     */
    public TransactionRecord() {
        super(Transaction.TRANSACTION);
    }

    /**
     * Getter for <code>finances.transaction.receiver_user_type</code>.
     */
    public UserType getReceiverUserType() {
        return (UserType) get(9);
    }

    /**
     * Setter for <code>finances.transaction.receiver_bank</code>.
     */
    public void setReceiverBank(String value) {
        set(10, value);
    }

    /**
     * Create a detached, initialised TransactionRecord
     */
    public TransactionRecord(UUID id, UUID userId, String categoryName, LocalDate date, String description, BigDecimal amount, TransactionStatus status, String senderBank, String senderAccount, UserType receiverUserType, String receiverBank, String receiverAccount, String receiverInn, String receiverPhone, LocalDateTime createdAt) {
        super(Transaction.TRANSACTION);

        setId(id);
        setUserId(userId);
        setCategoryName(categoryName);
        setDate(date);
        setDescription(description);
        setAmount(amount);
        setStatus(status);
        setSenderBank(senderBank);
        setSenderAccount(senderAccount);
        setReceiverUserType(receiverUserType);
        setReceiverBank(receiverBank);
        setReceiverAccount(receiverAccount);
        setReceiverInn(receiverInn);
        setReceiverPhone(receiverPhone);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Setter for <code>finances.transaction.receiver_account</code>.
     */
    public void setReceiverAccount(String value) {
        set(11, value);
    }

    /**
     * Setter for <code>finances.transaction.receiver_user_type</code>.
     */
    public void setReceiverUserType(UserType value) {
        set(9, value);
    }

    /**
     * Getter for <code>finances.transaction.receiver_inn</code>.
     */
    public String getReceiverInn() {
        return (String) get(12);
    }

    /**
     * Getter for <code>finances.transaction.receiver_bank</code>.
     */
    public String getReceiverBank() {
        return (String) get(10);
    }

    /**
     * Getter for <code>finances.transaction.receiver_account</code>.
     */
    public String getReceiverAccount() {
        return (String) get(11);
    }

    /**
     * Getter for <code>finances.transaction.receiver_phone</code>.
     */
    public String getReceiverPhone() {
        return (String) get(13);
    }

    /**
     * Setter for <code>finances.transaction.receiver_inn</code>.
     */
    public void setReceiverInn(String value) {
        set(12, value);
    }

    /**
     * Setter for <code>finances.transaction.receiver_phone</code>.
     */
    public void setReceiverPhone(String value) {
        set(13, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>finances.transaction.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>finances.transaction.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(14, value);
    }

    @Override
    public Field<UUID> field1() {
        return Transaction.TRANSACTION.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Transaction.TRANSACTION.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Transaction.TRANSACTION.CATEGORY_NAME;
    }

    @Override
    public Field<LocalDate> field4() {
        return Transaction.TRANSACTION.DATE;
    }

    @Override
    public Field<String> field5() {
        return Transaction.TRANSACTION.DESCRIPTION;
    }

    @Override
    public Field<BigDecimal> field6() {
        return Transaction.TRANSACTION.AMOUNT;
    }

    @Override
    public Field<TransactionStatus> field7() {
        return Transaction.TRANSACTION.STATUS;
    }

    @Override
    public Field<String> field8() {
        return Transaction.TRANSACTION.SENDER_BANK;
    }

    @Override
    public Field<String> field9() {
        return Transaction.TRANSACTION.SENDER_ACCOUNT;
    }

    @Override
    public Field<UserType> field10() {
        return Transaction.TRANSACTION.RECEIVER_USER_TYPE;
    }

    @Override
    public Field<String> field11() {
        return Transaction.TRANSACTION.RECEIVER_BANK;
    }

    @Override
    public Field<String> field12() {
        return Transaction.TRANSACTION.RECEIVER_ACCOUNT;
    }

    @Override
    public Field<String> field13() {
        return Transaction.TRANSACTION.RECEIVER_INN;
    }

    @Override
    public Row15<UUID, UUID, String, LocalDate, String, BigDecimal, TransactionStatus, String, String, UserType, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<UUID, UUID, String, LocalDate, String, BigDecimal, TransactionStatus, String, String, UserType, String, String, String, String, LocalDateTime> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getCategoryName();
    }

    @Override
    public LocalDate component4() {
        return getDate();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public BigDecimal component6() {
        return getAmount();
    }

    @Override
    public TransactionStatus component7() {
        return getStatus();
    }

    @Override
    public String component8() {
        return getSenderBank();
    }

    @Override
    public String component9() {
        return getSenderAccount();
    }

    @Override
    public UserType component10() {
        return getReceiverUserType();
    }

    @Override
    public String component11() {
        return getReceiverBank();
    }

    @Override
    public String component12() {
        return getReceiverAccount();
    }

    @Override
    public String component13() {
        return getReceiverInn();
    }

    @Override
    public Field<String> field14() {
        return Transaction.TRANSACTION.RECEIVER_PHONE;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return Transaction.TRANSACTION.CREATED_AT;
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getCategoryName();
    }

    @Override
    public LocalDate value4() {
        return getDate();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public BigDecimal value6() {
        return getAmount();
    }

    @Override
    public TransactionStatus value7() {
        return getStatus();
    }

    @Override
    public String value8() {
        return getSenderBank();
    }

    @Override
    public String value9() {
        return getSenderAccount();
    }

    @Override
    public UserType value10() {
        return getReceiverUserType();
    }

    @Override
    public String value11() {
        return getReceiverBank();
    }

    @Override
    public String value12() {
        return getReceiverAccount();
    }

    @Override
    public String value13() {
        return getReceiverInn();
    }

    @Override
    public String component14() {
        return getReceiverPhone();
    }

    @Override
    public LocalDateTime component15() {
        return getCreatedAt();
    }

    @Override
    public TransactionRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public TransactionRecord value2(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public TransactionRecord value3(String value) {
        setCategoryName(value);
        return this;
    }

    @Override
    public TransactionRecord value4(LocalDate value) {
        setDate(value);
        return this;
    }

    @Override
    public TransactionRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public TransactionRecord value6(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public TransactionRecord value7(TransactionStatus value) {
        setStatus(value);
        return this;
    }

    @Override
    public TransactionRecord value8(String value) {
        setSenderBank(value);
        return this;
    }

    @Override
    public TransactionRecord value9(String value) {
        setSenderAccount(value);
        return this;
    }

    @Override
    public TransactionRecord value10(UserType value) {
        setReceiverUserType(value);
        return this;
    }

    @Override
    public TransactionRecord value11(String value) {
        setReceiverBank(value);
        return this;
    }

    @Override
    public TransactionRecord value12(String value) {
        setReceiverAccount(value);
        return this;
    }

    @Override
    public TransactionRecord value13(String value) {
        setReceiverInn(value);
        return this;
    }

    @Override
    public TransactionRecord value14(String value) {
        setReceiverPhone(value);
        return this;
    }

    @Override
    public TransactionRecord value15(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public TransactionRecord values(UUID value1, UUID value2, String value3, LocalDate value4, String value5, BigDecimal value6, TransactionStatus value7, String value8, String value9, UserType value10, String value11, String value12, String value13, String value14, LocalDateTime value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public String value14() {
        return getReceiverPhone();
    }

    @Override
    public LocalDateTime value15() {
        return getCreatedAt();
    }
}
