/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.dao.jooq.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import sf.financialreports.dao.jooq.enums.UserType;
import sf.financialreports.dao.jooq.tables.User;


/**
 * Пользователи
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record7<UUID, String, String, String, UserType, LocalDateTime, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>finances.user.id</code>. Идентификатор пользователя
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>finances.user.id</code>. Идентификатор пользователя
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>finances.user.name</code>. Имя пользователя
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>finances.user.name</code>. Имя пользователя
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>finances.user.email</code>. Электронная почта
     * пользователя
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>finances.user.email</code>. Электронная почта
     * пользователя
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>finances.user.password_hash</code>. Хэш пароля
     * пользователя
     */
    public void setPasswordHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>finances.user.password_hash</code>. Хэш пароля
     * пользователя
     */
    public String getPasswordHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>finances.user.type</code>. Тип пользователя (физическое
     * лицо или юридическое лицо)
     */
    public void setType(UserType value) {
        set(4, value);
    }

    /**
     * Getter for <code>finances.user.type</code>. Тип пользователя (физическое
     * лицо или юридическое лицо)
     */
    public UserType getType() {
        return (UserType) get(4);
    }

    /**
     * Setter for <code>finances.user.created_at</code>. Дата создания
     * пользователя
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>finances.user.created_at</code>. Дата создания
     * пользователя
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>finances.user.is_active</code>. Активность пользователя
     */
    public void setIsActive(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>finances.user.is_active</code>. Активность пользователя
     */
    public Boolean getIsActive() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, String, String, String, UserType, LocalDateTime, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UUID, String, String, String, UserType, LocalDateTime, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.NAME;
    }

    @Override
    public Field<String> field3() {
        return User.USER.EMAIL;
    }

    @Override
    public Field<String> field4() {
        return User.USER.PASSWORD_HASH;
    }

    @Override
    public Field<UserType> field5() {
        return User.USER.TYPE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return User.USER.CREATED_AT;
    }

    @Override
    public Field<Boolean> field7() {
        return User.USER.IS_ACTIVE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public String component4() {
        return getPasswordHash();
    }

    @Override
    public UserType component5() {
        return getType();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public Boolean component7() {
        return getIsActive();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public String value4() {
        return getPasswordHash();
    }

    @Override
    public UserType value5() {
        return getType();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public Boolean value7() {
        return getIsActive();
    }

    @Override
    public UserRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setPasswordHash(value);
        return this;
    }

    @Override
    public UserRecord value5(UserType value) {
        setType(value);
        return this;
    }

    @Override
    public UserRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UserRecord value7(Boolean value) {
        setIsActive(value);
        return this;
    }

    @Override
    public UserRecord values(UUID value1, String value2, String value3, String value4, UserType value5, LocalDateTime value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(UUID id, String name, String email, String passwordHash, UserType type, LocalDateTime createdAt, Boolean isActive) {
        super(User.USER);

        setId(id);
        setName(name);
        setEmail(email);
        setPasswordHash(passwordHash);
        setType(type);
        setCreatedAt(createdAt);
        setIsActive(isActive);
        resetChangedOnNotNull();
    }
}
