spring:
  application:
    name: short-links
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public