spring:
  application:
    name: financial-reports
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ruslanagaev
    password: 1978
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public