/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.dao.jooq;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import sf.financialreports.dao.jooq.tables.Audit;
import sf.financialreports.dao.jooq.tables.Category;
import sf.financialreports.dao.jooq.tables.Transaction;
import sf.financialreports.dao.jooq.tables.User;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Finances extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>finances</code>
     */
    public static final Finances FINANCES = new Finances();

    /**
     * The table <code>finances.audit</code>.
     */
    public final Audit AUDIT = Audit.AUDIT;

    /**
     * The table <code>finances.category</code>.
     */
    public final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>finances.transaction</code>.
     */
    public final Transaction TRANSACTION = Transaction.TRANSACTION;

    /**
     * The table <code>finances.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Finances() {
        super("finances", null);
    }


    @Override
    public Catalog getCatalog() {
        return sf.financialreports.dao.jooq.DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
                Audit.AUDIT,
            Category.CATEGORY,
            Transaction.TRANSACTION,
            User.USER
        );
    }
}
