/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.dao.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import sf.financialreports.dao.jooq.tables.Transaction;


/**
 * A class modelling indexes of tables in finances.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_TRANSACTION_USER_ID = Internal.createIndex(DSL.name("idx_transaction_user_id"), Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.USER_ID }, false);
}
