/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.dao.jooq;


import sf.financialreports.dao.jooq.tables.Category;
import sf.financialreports.dao.jooq.tables.IntegrationLog;
import sf.financialreports.dao.jooq.tables.Transaction;
import sf.financialreports.dao.jooq.tables.User;


/**
 * Convenience access to all tables in finances.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>finances.category</code>.
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>finances.integration_log</code>.
     */
    public static final IntegrationLog INTEGRATION_LOG = IntegrationLog.INTEGRATION_LOG;

    /**
     * The table <code>finances.transaction</code>.
     */
    public static final Transaction TRANSACTION = Transaction.TRANSACTION;

    /**
     * The table <code>finances.user</code>.
     */
    public static final User USER = User.USER;
}
