/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.dao.jooq;


import sf.financialreports.dao.jooq.tables.Audit;
import sf.financialreports.dao.jooq.tables.Category;
import sf.financialreports.dao.jooq.tables.Transaction;
import sf.financialreports.dao.jooq.tables.User;


/**
 * Convenience access to all tables in finances.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Аудит сервиса
     */
    public static final Audit AUDIT = Audit.AUDIT;

    /**
     * Категория дохода/расхода
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * Таблица транзакций
     */
    public static final Transaction TRANSACTION = Transaction.TRANSACTION;

    /**
     * Пользователи
     */
    public static final User USER = User.USER;
}
