/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.domain.jooq.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Check;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function14;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sf.financialreports.domain.jooq.Finances;
import sf.financialreports.domain.jooq.Keys;
import sf.financialreports.domain.jooq.enums.TransactionStatus;
import sf.financialreports.domain.jooq.tables.records.TransactionRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transaction extends TableImpl<TransactionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>finances.transaction</code>
     */
    public static final Transaction TRANSACTION = new Transaction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TransactionRecord> getRecordType() {
        return TransactionRecord.class;
    }

    /**
     * The column <code>finances.transaction.id</code>.
     */
    public final TableField<TransactionRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>finances.transaction.user_id</code>.
     */
    public final TableField<TransactionRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>finances.transaction.category_id</code>.
     */
    public final TableField<TransactionRecord, UUID> CATEGORY_ID = createField(DSL.name("category_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>finances.transaction.datetime</code>.
     */
    public final TableField<TransactionRecord, LocalDateTime> DATETIME = createField(DSL.name("datetime"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>finances.transaction.description</code>.
     */
    public final TableField<TransactionRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>finances.transaction.amount</code>.
     */
    public final TableField<TransactionRecord, BigDecimal> AMOUNT = createField(DSL.name("amount"), SQLDataType.NUMERIC(15, 5).nullable(false), this, "");

    /**
     * The column <code>finances.transaction.status</code>.
     */
    public final TableField<TransactionRecord, TransactionStatus> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(sf.financialreports.domain.jooq.enums.TransactionStatus.class), this, "");

    /**
     * The column <code>finances.transaction.sender_bank</code>.
     */
    public final TableField<TransactionRecord, String> SENDER_BANK = createField(DSL.name("sender_bank"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>finances.transaction.sender_account</code>.
     */
    public final TableField<TransactionRecord, String> SENDER_ACCOUNT = createField(DSL.name("sender_account"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>finances.transaction.receiver_bank</code>.
     */
    public final TableField<TransactionRecord, String> RECEIVER_BANK = createField(DSL.name("receiver_bank"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>finances.transaction.receiver_account</code>.
     */
    public final TableField<TransactionRecord, String> RECEIVER_ACCOUNT = createField(DSL.name("receiver_account"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>finances.transaction.receiver_inn</code>.
     */
    public final TableField<TransactionRecord, String> RECEIVER_INN = createField(DSL.name("receiver_inn"), SQLDataType.VARCHAR(12), this, "");

    /**
     * The column <code>finances.transaction.receiver_phone</code>.
     */
    public final TableField<TransactionRecord, String> RECEIVER_PHONE = createField(DSL.name("receiver_phone"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>finances.transaction.created_at</code>.
     */
    public final TableField<TransactionRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private Transaction(Name alias, Table<TransactionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Transaction(Name alias, Table<TransactionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>finances.transaction</code> table reference
     */
    public Transaction(String alias) {
        this(DSL.name(alias), TRANSACTION);
    }

    /**
     * Create an aliased <code>finances.transaction</code> table reference
     */
    public Transaction(Name alias) {
        this(alias, TRANSACTION);
    }

    /**
     * Create a <code>finances.transaction</code> table reference
     */
    public Transaction() {
        this(DSL.name("transaction"), null);
    }

    public <O extends Record> Transaction(Table<O> child, ForeignKey<O, TransactionRecord> key) {
        super(child, key, TRANSACTION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Finances.FINANCES;
    }

    @Override
    public UniqueKey<TransactionRecord> getPrimaryKey() {
        return Keys.PK_TRANSACTION;
    }

    @Override
    public List<ForeignKey<TransactionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TRANSACTION__FK_USER_ID, Keys.TRANSACTION__FK_CATEGORY_ID);
    }

    private transient User _user;
    private transient Category _category;

    /**
     * Get the implicit join path to the <code>finances.user</code> table.
     */
    public User user() {
        if (_user == null)
            _user = new User(this, Keys.TRANSACTION__FK_USER_ID);

        return _user;
    }

    /**
     * Get the implicit join path to the <code>finances.category</code> table.
     */
    public Category category() {
        if (_category == null)
            _category = new Category(this, Keys.TRANSACTION__FK_CATEGORY_ID);

        return _category;
    }

    @Override
    public List<Check<TransactionRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("transaction_amount_check"), "((amount >= (0)::numeric))", true)
        );
    }

    @Override
    public Transaction as(String alias) {
        return new Transaction(DSL.name(alias), this);
    }

    @Override
    public Transaction as(Name alias) {
        return new Transaction(alias, this);
    }

    @Override
    public Transaction as(Table<?> alias) {
        return new Transaction(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Transaction rename(String name) {
        return new Transaction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Transaction rename(Name name) {
        return new Transaction(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Transaction rename(Table<?> name) {
        return new Transaction(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<UUID, UUID, UUID, LocalDateTime, String, BigDecimal, TransactionStatus, String, String, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function14<? super UUID, ? super UUID, ? super UUID, ? super LocalDateTime, ? super String, ? super BigDecimal, ? super TransactionStatus, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function14<? super UUID, ? super UUID, ? super UUID, ? super LocalDateTime, ? super String, ? super BigDecimal, ? super TransactionStatus, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
