/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.domain.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;

import sf.financialreports.domain.jooq.Finances;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum TransactionStatus implements EnumType {

    NEW("NEW"),

    CONFIRMED("CONFIRMED"),

    PROCESSING("PROCESSING"),

    COMPLETED("COMPLETED"),

    RETURNED("RETURNED"),

    CANCELLED("CANCELLED"),

    DELETED("DELETED");

    private final String literal;

    private TransactionStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Finances.FINANCES;
    }

    @Override
    public String getName() {
        return "transaction_status";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static TransactionStatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(TransactionStatus.class, literal);
    }
}
