/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.domain.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;

import sf.financialreports.domain.jooq.Finances;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum UserType implements EnumType {

    PHYSICAL("PHYSICAL"),

    LEGAL("LEGAL");

    private final String literal;

    private UserType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Finances.FINANCES;
    }

    @Override
    public String getName() {
        return "user_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static UserType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(UserType.class, literal);
    }
}
