/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.domain.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import sf.financialreports.domain.jooq.tables.Category;
import sf.financialreports.domain.jooq.tables.Transaction;
import sf.financialreports.domain.jooq.tables.User;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Finances extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>finances</code>
     */
    public static final Finances FINANCES = new Finances();

    /**
     * The table <code>finances.category</code>.
     */
    public final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>finances.transaction</code>.
     */
    public final Transaction TRANSACTION = Transaction.TRANSACTION;

    /**
     * The table <code>finances.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Finances() {
        super("finances", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Category.CATEGORY,
            Transaction.TRANSACTION,
            User.USER
        );
    }
}
