/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.domain.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import sf.financialreports.domain.jooq.tables.Category;
import sf.financialreports.domain.jooq.tables.Transaction;
import sf.financialreports.domain.jooq.tables.User;
import sf.financialreports.domain.jooq.tables.records.CategoryRecord;
import sf.financialreports.domain.jooq.tables.records.TransactionRecord;
import sf.financialreports.domain.jooq.tables.records.UserRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * finances.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CategoryRecord> PK_CATEGORY = Internal.createUniqueKey(Category.CATEGORY, DSL.name("pk_category"), new TableField[] { Category.CATEGORY.ID }, true);
    public static final UniqueKey<TransactionRecord> PK_TRANSACTION = Internal.createUniqueKey(Transaction.TRANSACTION, DSL.name("pk_transaction"), new TableField[] { Transaction.TRANSACTION.ID }, true);
    public static final UniqueKey<UserRecord> PK_USER = Internal.createUniqueKey(User.USER, DSL.name("pk_user"), new TableField[] { User.USER.ID }, true);
    public static final UniqueKey<UserRecord> USER_EMAIL_KEY = Internal.createUniqueKey(User.USER, DSL.name("user_email_key"), new TableField[] { User.USER.EMAIL }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TransactionRecord, CategoryRecord> TRANSACTION__FK_CATEGORY_ID = Internal.createForeignKey(Transaction.TRANSACTION, DSL.name("fk_category_id"), new TableField[] { Transaction.TRANSACTION.CATEGORY_ID }, Keys.PK_CATEGORY, new TableField[] { Category.CATEGORY.ID }, true);
    public static final ForeignKey<TransactionRecord, UserRecord> TRANSACTION__FK_USER_ID = Internal.createForeignKey(Transaction.TRANSACTION, DSL.name("fk_user_id"), new TableField[] { Transaction.TRANSACTION.USER_ID }, Keys.PK_USER, new TableField[] { User.USER.ID }, true);
}
