/*
 * This file is generated by jOOQ.
 */
package sf.financialreports.dao.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;

import sf.financialreports.dao.jooq.Finances;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum CategoryType implements EnumType {

    INCOME("INCOME"),

    EXPENSE("EXPENSE");

    private final String literal;

    private CategoryType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Finances.FINANCES;
    }

    @Override
    public String getName() {
        return "category_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static CategoryType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(CategoryType.class, literal);
    }
}
